# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:pjedXvrx84rAtSmiQp7vetSPlzrDrzQpG2lBwTYgbLuffhIaSbqyIA==,iv:8X3nJRa82ymqUJzRzcPF1cP5GGiRyuNR8PmXvt6UvUk=,tag:iC1CY9eETayuv18RdwMlTA==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVW1tZkVNNUNxdjhKa3o2
        NXE2UzNCZ05VQ0dyeFl6TUR3UTQ4U2RUMXh3ClA4ejRZQ3ZLUWY2M3RqcHIremFX
        UTlmME4xUGYzREhYSzBIZjhLSjduZUEKLS0tIG9rWVNqdlJVR045V1YybXBvdVZm
        NmJ2clk5Z2E0RHZxaXZYZ2RPZnE1QVUK8HPSYK0H9jJ6W6eCAj3zGlew+UeUSTfq
        UVIA9r+1hPn24W3UL54fQjjzIgwWjctrcllvUVq/9igK+QYjM9taqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:08:50Z"
  mac: ENC[AES256_GCM,data:pdyYVbdbPjNLYmcYOCPoTxElPAnMzCiVAdzRQtifGEkZcTLEUwV4bgia+rK3KPFi679RaH8NOlLNCCC+6/zoQAcdkUZ443/oVkde9tzT3ntardTz/CNWtrWoRWpWfHbQtWFMEhzS81RQuHzTxpb9yWuTvo1GOMyuM/5qF2BagwM=,iv:viPRiwRinU41mzJVAIbuIFn8qIaT+6U9p0te0KJ6An4=,tag:QQjEZSxdw9MzUokMQqRTWg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
