# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:LizA7rZGGHm0Q/lNlNp0vHcPmc+04+lkfEWzNKgU8fViO6cofKx1Rg==,iv:9OavbwU4LNV8EIV95HgAOEy5iq6D0yZtXlwtLKC58N4=,tag:hgk2CnDGOcDzzHtoGZnS3w==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUFdHcjh2eXVqZ0pLeXRw
        cjAyRDZINE1zN3Y1cHhSbGtsNTl6TXVNMUdvCkpoZFZjR2Y5TDR1cHVHZGs4TlBy
        UlM5S3ErOFhEWXlud0trZWtpT3llVncKLS0tIHRNcSthdUo5OVI1M0pKZDVBUkVj
        dTI4eFJPWVgvc1dzeDFVRSs4b0p3WUkKjc+xTcmRyBJZep1cAmOHsVMTgGzdiC/R
        lkjwD3uYT7R0sLJyiYocBBIS8GOLLlcPVl2bsXXPAIhJ7bhLZOOztw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:35:28Z"
  mac: ENC[AES256_GCM,data:i9kjBUXg8s5impeo0Fv+0hbb54XqAtTMeRICc/swHQSxVLuRpj40Iw7WNk+mgz7O/PWczmg/8UbJF9xOKpIuXqnFhURUkG7RNpzTasKrMlfL8UAgJJ0e+/3hNsEOFgtY5mRYQ7Rlhfb8NXRs4pfZZJaZvwNRvvAMIEgWk4yr7Us=,iv:voWUHY/PvDBjMlu9SoukHg04uvXVyIUGqsMWkjFVzrU=,tag:qezKS9PEkVz6JeMAAHb3fw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
