# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:PnIhANwWLtTCJEJltxsMfJFJNPhvNTIfmveSuNochSqzAjLdntYgyw==,iv:+0gYJs15Q3KcnymY6lBNwr7YwOoWIRcB3JrQZq+Y66Y=,tag:2Ta3DxiPtXV/yDF4OQkT/A==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaDV3eDlka1dpd1cwelRa
        YWJ1U0gvZ2R1ZTQrMTNYOWp4WlU5NTlPUEdzCjd6ZzFPeEgvNG5Wb2RpbFAra0di
        M3RZN0g4RTBxN0tXd3I0YTRRdXBSODQKLS0tIE9RdnAzYmh6V1ZtSndUcit4U25Q
        UThMaVhkUlJ1eE5reG5PYzZITTNUemsKkJhOizdtIywMdeKzHg2En4OdZJ4p78oc
        UIyv0X6Dc0HepCDH6kqKVqhQclhpg5lOE3+Uo2ayd39owtuc/u9rSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:00:16Z"
  mac: ENC[AES256_GCM,data:YtsMsAC/zU9WIh/KGE721Et7LeJAKD7pbbgQ5KQZLlbkTSo1Y03zTNDtJEodORRytkXeg2ldFYrATcJycm1l3FcylExKZPpfB6XePBJ9mV5uDARfbVNEmLYYmm7u4U6SOcQfC4hk5vt5vMDbyGeHtJfK1RFCz3oPVvgxpsNkC1s=,iv:qlBjqgJA6RTVBK1CKchpwO97wZYpFDKAkdwhFHKVgjA=,tag:9F9BCcivYtSVurzJktGbQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
