# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Bc4Tf8k6pbJnTuJk/LMqyb0h4XQF6smVxFGdTIngJu4=,iv:2IxyC5dstILmNdSE/hsSkrOoklfUep06A9PULZdTtYc=,tag:7gbb1j27acqQXqTOrtkqOw==,type:str]
sops:
  age:
    - recipient: age19nxy2s6an4akrcwya68ynn0ymlsuq80uxnz0r09q360r8ftnx94sncahkw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTlNQVjBtb3c1Z0RHUkxi
        Y3FZcXhzaWI0NXJGVXFWTXJuUjdjTXF6eFc0Ck95MVgvUHg0cnFkbFVqZ3FScjV2
        SVQ4VE1ZMnNoRndrTnFHd0U2YkdLNGsKLS0tIHpHNDF6NzRJY1B5N3ZDdTFvYWNZ
        L3pNd2VtOFVNWWtyazh4ZUNrU1prTTQK2uaGu3rh/AjB5i5Td+f2tNwmFzKp0jPa
        hXer76D0dP8OUfZRphWtYfg93nZMxHUCM5LvBsqCGUatuQJCLAfj9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-28T12:34:01Z"
  mac: ENC[AES256_GCM,data:/XaShF1t4XGQFuvD3WYVQaW9TmeQiIE7/LaU76t8xwYS39Kk5BnpE4BjFD8gYUMbW73TrFU8bHTRgGeRWcKAJDHWbhSbPUpJXP5VqqVcK3zPAtfO2ZCDLth9fnWY6ZQuJhOv/tsFIWmGIOrYkRn9nsOsmnnrsYnh5AaFGxDjhiw=,iv:L5+obBOYrJH+l4IwaR+rJUKL8WEBLZCMoXujLjadSX0=,tag:69rrjX3vr2YSEFaKz+pE6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
