# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:A2zN2sThQJTF0kD1RxVqiVirFyhloXyVZ5BMNhNd/qs=,iv:0EMQrA2LC1l9QHE6KpA7hL//Fbj4jL5Xl6lpfZo0q64=,tag:OBqF8HhPR4m6d4VZl7auhg==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Q3VNK0hOTEp6S3Z3Vm1o
        UCs2YW1hWVo3Rkc1dGxkNXllbzFzcmhBS0RZCnpvZk5vV1FmbTRWbmhUSkxZVm01
        SXFqaGorN0pOVC9XMGdiQjRDM09VcDAKLS0tIEVpS3I3OVl5NG9nQ1J2SWdmNTNq
        VXlVUFlZcjZIc2JReEZ3Q3Z0cUk2SmMKUexO+y53aGa4V3xPg9LkyHoiqxHBHHQB
        LxxPOWtBD98jFW8zlUX2qU1svNoSaF8mxYU40kxvL1HnC8vVWChWZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:00:16Z"
  mac: ENC[AES256_GCM,data:UIk/7voo75M/Uqbs6LLD5XMQUnoMHkCSA4e53ZJS97a/6FvrLpwTuvmjg880Oq5IBVyY3JO42kFIJSEfpUrqtpFMu4S6ejtyu0ghKjLGoYGnHay3DIeylhwzviJXvqG4moVYl8COuD66hVf+i/IGAuRNONudh/lwybMRvPzfzTU=,iv:RvL7JAI21+FTUID2DFZSZEmGob7RaE25ncBI4oEQugg=,tag:w60N0WHiow1GzdubmK3v4Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
