# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:rOWKggG5EH19y0K9w23f2bdG2+U+aHRFlSA7sa+EhE0=,iv:OsZQ4nvWEzRvUP4t3YRTI724SdhgqQQyCMKFP6DcvpQ=,tag:r3zpQGSiOnZv7kXk8lWeoQ==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RVY4T1RaTjZuUnhrVEx4
        VVlOM1dnVUw5TmRXdWQ1ek1sZk9ISGVPMkNvCmhSWEdlbEpSd3NkSmtqS3pDN1R5
        eG8vbkN2RlFnMDY1T0ZrVkhwS3VlWXcKLS0tIFZsbmtkaU42V3lQaFFMNVJkakts
        eHJyU0Fsd3FZMlJycWtXMU0rQ21EQXMKuhdghNSLVqZHIn2/0wqhCv4gIQtsQgKs
        RneI8hwAbKNWZZMQNuW4kSgQNsjObVB2NSpmE8eMhc1Yv5XEFbBa0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:35:27Z"
  mac: ENC[AES256_GCM,data:4nB+m/QTs3uJqhw84iQ1+l7yw1FlE+JxMYEpxWmoJQjgQYc+mvlkv35u2wk7J54dxjj8SNPc3ZhKxdSZUmDh2pSMa7T3Osgj58zCjgI/XGGIQp+t6TfoZOLXZ3RSrN2No6AH/F55+8q5FsXwui0coCq5BTwP76y91L3i5CuYr3Y=,iv:ThTX9Ji30kFsbQQGjqHwZZCGKq7vNPAvwqWZlVU1/0M=,tag:odQKAC45SplLyhJQjL3c+Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
