# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:lkl5+g2zgEC+NdQCg0js16VEPbR0Qi39PyayT1FZVzg=,iv:2lfu1/ltq009r3u97dRrTd2y1O9TafybaNwTWG+n+fc=,tag:c9xcPERXsYa4gtv9EbhXSg==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGc2IxaEY2eGlnbGExRm01
        WGZNc3ZEc3J2Yzd0a3J5V2U3MXJvOGNyUzJNCnpPemx6SkhCNVpCYkswUmpwbE5M
        cThnOTR3NGFGL0IwQlVObEZmZ3lqaEUKLS0tIFFNSnRVLzQxNUViNThKRUNBS1J1
        dWVDYVJwdEJ2ZW96YUFKNU1pWGw0clkKm/rBcsp9MkfEOIRiRqy2b1+ft7nCPxEN
        HLyBMFogVwS8yAl5yE30jS7YEoqGd1X33O2KYyuvJUsN5OmJU2wjGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:08:50Z"
  mac: ENC[AES256_GCM,data:4RxvcVNEMXoSVnn+69UyqAISILiryiuWgxJcZKoieVcGluVFrrlfzPBHJb7NOl93XAqbhbGuBFycsEX80KOWcLSlovHitpGvgtkY5ux+sr9Somf8vno71X9GcJRhwXlq/ZMavW0iUUFjCpN+V0Se5U1aADx4MjjBGC0ibUsOEto=,iv:rjJelP2F9mPJOU9qZZi7X4pEyFD6E/bBmCRKf3gmCds=,tag:1R2xV0BT1dgi8eTfQhU2Rg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
