# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:13FwVUMfIjvV11rw0Z6YW1W6a8iDJpmat85Yr+N/s6Q=,iv:KpLFFi5CV8Y2UntBpkyBSWCDSs+Tn3LdZ6WjcW/pwpU=,tag:C99Xz3YkC1HjrREPPsOnmQ==,type:str]
sops:
  age:
    - recipient: age19nxy2s6an4akrcwya68ynn0ymlsuq80uxnz0r09q360r8ftnx94sncahkw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ1QySURVbTlUY3gzTEtU
        VWJVdnk2ODVOY3BXZnYzaENZbHZnWDdyZW1FCmkzOU53QmlKVzY0cWxpNjBMYlYv
        YWNTNURaOVlQemhVWFVsS1RjU0swcHcKLS0tIElIRmxrRlVadlFHT3VXU2kycEN4
        dG1SM2RlVnFmT2dFamZzQ2lJVTF0aFEKtNTJdOX9nKP7uMPruHfCU+uqhkLeeRqo
        RfUA0XpgUpunT+hSb3Zxi22ntJpC8aI0kWrzrJzClJPIB/gtaNbJTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-28T12:41:32Z"
  mac: ENC[AES256_GCM,data:oQUHDuxbBCQrjzt0t7hPzZ9RtJQgxSST/Msb4d8TLxOBwJPi5lGQ7kQR5LwQfhXCqZAri5a/st7hq1lAHWuvw+SP9AvyVC9MMdWyVb16X3sMmfVTRizO6qTubl4l/9GnrqDgI5wXYrvRSVMHte0a/IVgi87227W8bXYFEmwaarU=,iv:qYGTUqwwLc6Lhb6E5fvt41pZ49Psc5n+cm/bgE/S69U=,tag:V8bqNZRxgrrZZ6PIiv4D8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
