# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:/gHRfa8RcoxshrkoYQq/MtEjxO9UxuhOm2J/AcsIKgdQGbAfFvVrC2TVT1b/kDjBgf3zpQgZdsUsy4LtPVj4OtDJjwAQCdLAkwKGPg//ADklJCI+WbG8U9EqxYKgU9ClPv/jiaogsDqo/G7wOKzGQZNMjLGphzHGO1x4AONy4ZFBlv6jya+JANzdAWoyRHuZ6T4Iwdwm/eQH8Ifi7qLdZt3eaHQhAYsvF+nIkUqY8JOOH1QB,iv:zcsVW693T+BwKjq6cDtoBbxHvWaxsm4tgib+mPh8nf0=,tag:/jckTv2TaT2TDMNwhlRl+Q==,type:str]
sops:
  age:
    - recipient: age19nxy2s6an4akrcwya68ynn0ymlsuq80uxnz0r09q360r8ftnx94sncahkw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPamxYaURPMm8zaVhPZ1Vs
        WjZCZ2NUVGdtRG5sNUFjcURlOWFLRmprZ2tnCms2cmVpdytOZUVqcG9xWFhEbFJa
        ZExQQ05ya1RxUXRFQmsvVU05UDJkNkEKLS0tIHlpaGRuS3BPZ2N5eENkQ00zQU5s
        V0ZNcC9lK05HV2NJdEdXYmEvNVNkamsKsbkyI0OKxN9PaqPbBNc3FqBtUtPTKuds
        LBygmlwkjXPyJUhcwl7LLB5fpvsr8W4tPuGieYS9/OFJi7FleBvLIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-28T12:34:01Z"
  mac: ENC[AES256_GCM,data:mwdwBCVsVWrup7JyIk2HhJR3UvIjDJKzH4bWG1tKaV2y6wdQjpY1mGytBXWbiRb0svwexfS4fq9wMxmpOdkt3LqO1l2Uyd6CBMYooPw2L3v0kNtBatv8bHWWi7G2fwWTRs5MlzCBFTahA5gf25FQtqPfJWrtSwh91Pp3VDZ1yAo=,iv:nrxtmktYjHXu9reUMQmbDF1+1buXFgd4QdPh3D+Pu34=,tag:kbpCOd6r4B4pi7KCfzvpjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
