# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:gkQwN3Y9RoX+GbrqG0m/L/RF2TVSFWd+KSHZuB88+ufozY189/d4HTji0RajHp6xaPY+9AMq5M4QU76QHGh/oYQU2HuA9Vl/PnhpFJNlOvH9T0NIag+aXse7kW1Gg2X2CHDjH5R9marH7hewrzRa81Hl+xZ1KPaKQzCUenVFLQ6r5msTgWyfvU6j8PSPba4oxOLJQIUntB+mCUQv8ehegzoSDZTgZMwrjVUaL5d6Dgevior0,iv:zMIzipTtOkmUfq4pYs0Sw15X7/x47Rn2hl0Jo/h9mkE=,tag:vqklutpRrENcrCoJNSP0Hg==,type:str]
sops:
  age:
    - recipient: age19nxy2s6an4akrcwya68ynn0ymlsuq80uxnz0r09q360r8ftnx94sncahkw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySmplMjV3dW82NG1YRmxt
        ZkhjOEdYZU0rWDRaeVBkb0hiNUM2VjR3VEhJCldERGVtckFiR0hVdkJBWUw0QXRO
        UHUzU2JydDRSYk1Sdm5mQTlMM2hvM3cKLS0tIE83WEhuVGp3S3ZUQVFTRGgxTERG
        bDh0QkFkUkpEdjZJWHN4RFZQTllRYWcKw/e0dmQjWgo0evcHy5iaz9dpM/OGK0DI
        0MoLEOptFqBGZ9J6j0/0pQeu7AYcDW/OHbsgG2qsU63Ho29hwtIPcg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-28T12:41:32Z"
  mac: ENC[AES256_GCM,data:1CU3EhlZ5/ppENzYa+/+bOqNqj9gG5HRpyAmMli82WOt21UfWp7UXmlL/TBRP23y7bVSTAz1Cuu4kklitTKGeYSrjDS2x5fJ0YxxuRvhaS9UOasR0dyGnD+J7g5/W8DCygMqIxdWv/keX9zduj0yw3QgERF5gsUVRTs8Tv1BHKE=,iv:KF07GVHzDigk6roDXSEhDfBov7EuhWS6lGPQpIu8aCo=,tag:gi5Xo5CHHV4/nVUxJ6YeeA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
