# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:BhKz9NMmluIHs4LAT4PnyFyMTLK1LBHGPqp30EJ26bxqQZawEyevdOEvHvVjflSVbHpuSTgNSBr6bl7BOII1hNA8vMoXkPKja4Dajevbsb7wNXEdJK9sO9EcBFlWl9PyAo2y+MetKMyttOg2+U77ld2bewit+1GK4J4bmq3DDnc8vc17Nq6StC+dOwIEtNiImJ0FFUeogP4ajmzwrrSIDRZ280aPpE8SQznAs/52VCNfQKoq,iv:7amuaDh3FxbEzcQqnHu10n/IWhezUBa7yhux5o6xh2E=,tag:2CUSnuMZFZS/5FoIqM7e/g==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWTJVYzRkV3dJMDFpUHMx
        bGVIdE5hVVE1NUdWOHBqOS9ML1drZzlocHkwCnU1dnVnWDB4L0ZSRjRBb3VKd0FR
        Rm0vb2ZRV2FmQjZydnRMazFuU2V2cFUKLS0tIG1LSEhTMUxwVGIyNVlxU3NYVDh4
        aHZtVmk3SFhaUkYrVVNvMWxDNEhlYjgKQHbgEh+aUFjzgy0wgrrExXx//UIW2gRf
        OjAYoGAXfU/oyxzdanomzhcqoe1MmYq5lyIMgDjqIxXPO+FEYiuEmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:35:28Z"
  mac: ENC[AES256_GCM,data:rcewsl4K+Wu7hLdqGBAftjMB7mshHe1wQk6r6hAdMwqKHCNiE8E+y86hJHu+A3AJqh5PACFomG/8xgPTdmi1m/nWnt7ZwKrfGXLOqI9jqKbQz9PJAboezlmGdWE6w3iFJHEn9ri68yxPsvYEHmoeA+E2b/8PKPZHWirl5IrfE+4=,iv:ohOpP68H/LeK3LzDtkbR9WZs6ywhOsympoq/42xrSu4=,tag:/Yh6Iq7m+j2eNaMV+iqVmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
