# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:n2DwDGJ4MMvq4Dldy1iBfrhNOCzyETk3/8xAvLdGtTP+2NUsFnyKX6Gx6+QV2d1HWo0nA/yNaeMsBJ54pud5D+UwF/BuomgZG6rdfteH++Dt8HL4n+TYgLV9U/sxF9c0eD1aq55pNDZj5eUdGFw615l1jwq6g9E1caxjXnf/t6QdxfHVB1bAPpqRtZWw+nNgBUpSMJ9Zf5qnqtTqKcRfyuxU2gZ2RwYhENyszSKI8Wt01usw,iv:WRFlDhxz3wFirpGXm8uMA5Bw6yAb7RDAZhsGsx3p47Q=,tag:82JGXl5VCDk9zYvv0HPapg==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxN0JtVm80anJPU2prRTRY
        MGd3M1dHMy9qcldVVXBQeWlpM2x0dGpocFg4CkpJWVFIYTJ4blVYRWlqcEl0Skp0
        akFXZjNkRzlQODFWTGJUYTRWSnBpVVkKLS0tIGtxc2ZIQityd2NuM1Z4TjFEdVcy
        Zkt5V0J5b09ncWgxQ2ZSQ1JlS0hSMFEKfEUmq+NoyTntpln1B2aH1s2zfYWxX7rm
        tKEFekSSfdsotMHC5aoOdRLn9/3a+2C2HrvnZbfgp1f/DYzq9JgvFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:08:50Z"
  mac: ENC[AES256_GCM,data:x5ys40ysjas+58eV5+7f/qm84G60SetrZrigU/mtCWW+o+gpEc/MN9P8WPwEwpWQQUJ2E4b6JhK8kQpjGrX+2AiNz3UhPh7nHHv4kcJHmJjg+OGyBdfM0R6vyZ7HmHH+B1uh5amMIE6kGHnkmkZ7/TQvqoO2Z8uIDiuCD33htqg=,iv:njVciav94NG/wcThzTCLew/WLvLNZX9Y3LHhANLaqEU=,tag:FLyqDu3GDru5sI8a78WtDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
