# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:/Qjq0z/iJMDdosWYkh88x070OuHZAS0dHUiggf+uurXClTB+EkQN6jgzzaIX7QFAjz6ZiavPW3eTRT5C+dHULt76O3+HC2uIPVFC8ep7JrbQbsxo/zMVJHEuouEsapVajhdBcP6jkhMo/Q2huA7UtN+C0TyLht5EjhL+yNGwjBQdLVqTUCiQhZHQ/oUF4yG22bQSTxt0MGgsPrzqdl2LCXfduv0t5yyCmAVNTAVoaDsGMuiQ,iv:ASMVVYQn02HrezEWfw0bX9d6dzjWz/GMz/ng4lminzM=,tag:IfUpadtQadflyQOgYGTN9A==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWmMvOHJDVzRkYWhzWlBx
        UXhTM1gwWC8xRWJSWHB4S2EyQ2h1NXVzNG04Ck5YTlplcWx6TEtmak5KeEUveUJB
        bDgreGl6eFcxQlluQk50ZGFZRzdTaWMKLS0tIFh5OWw5QU5uS21XM0Rydzc5Tjd1
        MUx4eDBqM2FrblFyUFlZdFVJd3F0TEkKS90Ll5ILKwsZufC2rqq/tY/7nngOo/YF
        LycCSOrn1UpVxgaCASm7hcHp908CL58RpFt70Eapa1tpznAJbG2kHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:00:16Z"
  mac: ENC[AES256_GCM,data:TFJd1Ovs0hOWHtCcppQu1cv3k/ZbVPz318duqKFkMgEcWmA/qcOPzNh/9plcrhIVGlI8+ccMQEo5fsThGhss242qbYrtUhrskPTpC+JH1QO6ucWI7qlPmOhYXq3yYMbWM345oaQswoxYg7jNLjvqR9yju5fat91nkgfg1466HSw=,iv:xQQkWMn22B5jP1H/0etWKWf0mSN4OaCkB6FpMeXwHMM=,tag:MfG0KbsGm3BCfdVIdTNtnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
