# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:hDr5cV5bBpqP4v4rXp8Bjz1uR5xivFtKw8OCfFuZ2xPhn6m4rh9XXA==,iv:bTia7jIDTd5KyP+pNlqo4r8sTTqYJgUGQts3Pte57o0=,tag:kL2yPBQdfxpvVoSuQ/MSXA==,type:str]
sops:
  age:
    - recipient: age19nxy2s6an4akrcwya68ynn0ymlsuq80uxnz0r09q360r8ftnx94sncahkw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlclI0ekQ5RFgvOTdnQUQ0
        aEp3NlFuU3BveXc5dnZSZEtnOCtMTURDOWdJClBZQ1BOcFk3bU5qQ3pxTjRNUkdS
        aUVZWjRKMGtkYU9abzlPRmNRU3J5UVEKLS0tIDk4aGhoK21ic1ZQMWt5WlEwd0hC
        SkozZTdGekNjRUZhSXFMUzQxME56L2MKn33gl1XuKBo2KrzcEOaYf4X6BFgSAESI
        DeypqY3WuZGFjxsKXISOsVourvMInMm6eqj9hqR3NXjvxLDHr0AOpQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-28T12:34:01Z"
  mac: ENC[AES256_GCM,data:O9xYo4xj8eUm4WGFNEzs+QXPsOtd2MRzc9Wc0dnyCmApBv2InnGUxzWsacVdT/pTxF32zVWJ2MaU8LugN70gLN+201cpkJRcrUbVsF3AwySD/DtPktMDetzS8yDhN8Ua4YCKt8szfmUo15VQM1DV92FT5cJv7LgA7venHDKmfZE=,iv:GQGOjEchqUvcWV8LZ7F90wWdX2JpvRvzmraZob+jNjI=,tag:YewwLZEnUw8ougVZCaNcUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
