# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:AHEsdDf1OnAvRO63GfJxc3yJM5uz3h+Gbi3181crp48iXL0p/82Vlw==,iv:6p3n/FtmfdL6f4YHEU3Vtdaoi/4mp80Jqu52aaR58CA=,tag:DQXvdczuUv8vnQ51JKandQ==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUTVjblc0WnhaLzVWU3BX
        ckFENDlFYk0zYXY2OTZDZzVYNmlwdyttWTF3ClNYaXN3bVZ0OExiMy9RZmVXSlls
        K1NBTno5YWtvQTFJSnJIejA5SERKNUEKLS0tIFd5Zk5rR3RkU0JKdVdRT29FKzIw
        NEdGbGZCdVRURmMxZHFlWTd3UThnWTQKb0XpG9pi0fFJZ6vDvWaE8qLJjzFrdDKr
        8fFMLF0y2iywzxaFHJZnw2LU9RrZTfV9jrxbkXa2y6NX8gRt+ltvLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:08:50Z"
  mac: ENC[AES256_GCM,data:BYcQPxiz/3z/dFN+/KqZCNka7aabDmbn4SRecSPtlWpKGcpjmn91eyCGimjteAjgzKnYOomRk6lEpz3K57aknaayfjea2Lco//jLlIFtRkdm8CBPKIgky6bEqfOBqspqEnevuPFprllgMio1py/+aanUEdqDt/knyPshC0Kng/Y=,iv:h2TL8xhwH5ZXm8v5vPsbZ3IhLZJc3R+UiLmI/YE2FZ4=,tag://EJRKJW9QJ/Qg0EGxIE0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
