# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Ffwm0WD4W5y4GGGdwOXz9ZqaFPHnSMhFe4YagFpHUD9XIRNeF5H7rQ==,iv:GYYwUOCRcdrEXqAmAUFCQ/2yuze5r7JGpl7nITI/UXU=,tag:jvmvKsm+Ohg4U6R2eNKD+A==,type:str]
sops:
  age:
    - recipient: age19nxy2s6an4akrcwya68ynn0ymlsuq80uxnz0r09q360r8ftnx94sncahkw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dkN5OERjNmxNNkFVYnVL
        NDlUWnNhbjU5ZGh5M2JsNzBWNGdpQ1o1SHprCm1Jd3lqMVdUdzNOc2lDYzhtK1R3
        cUlaZFBqNFlVL3Mxb2dPaC9qY2FlTncKLS0tIG13TFNpaE5PZ1lZSXlmeDhDWkRl
        NUYxbXN2K2laakVGQXhmNHUrZUdSdmsKwqrsWLqaYCyJoJOHTlogfAh4JnzC0yfh
        sth7zJLdunCPExaUWbw5p28yE4a2QQ9g/MYUvB2b8KDPID9QoBIXjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-28T12:41:32Z"
  mac: ENC[AES256_GCM,data:2MrMYhB/JZ23Xpp+MVgnJJ/H50MkBYRgLaXTOsdQ56n1NRx3qLe079sk6bxJ9OctEcqFnXXouGJfOJOg7/MTQYfpu4yxJv6Q36jBjXkeZMW/k4C91Fw+at5mWBHdTzqsRpcrVlnfymnycrjF+Rd39219ClDPipcaqVmA9kpf89s=,iv:lWeQXdjlwmvaTiWA6MRuMHE6w2Qg148FmOi+P1GHQMs=,tag:Pg292EX6isrQOJiH1d9toQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
