# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:PMrjxIhatELp2SigT9vFFIoOiXIkhwLQCBo3/0vP578VMnS6dMYOIQ==,iv:mYf1pvaQCURvNCLdl1mz6JVA3kaSE2fJzCcKkUBC7Cg=,tag:SQ8JK/qE3AZ9Q98hWocJWg==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbENjaFptcnZlaFo1TUxV
        QVZTSnhGR0hNbS9NMUs0WUtyakxuVVpvb0dBCkN6NGs2eEdUSnYrRzlDV2J4dERw
        Wk1Sa2p6MzlJVEpwb2pzcDVPSis0UFEKLS0tIHdNbEU4d0FpUEtTZkZ6SE53ejB4
        b3BSUVJQUTZWRVZxZWlXTWNKeG1ublkKiQFe1tgahSXaOVxuZdZBBLqZVZOH4EKC
        yhpXlR1ialphNfOOO8iY6aONJqnDuImAL+t13hU5TwmK+I3rXuhCoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:35:27Z"
  mac: ENC[AES256_GCM,data:5NQeQdpY366NxLP43njGcBXyZ0l1UkIday5EjKrNTTRsaXGL9nkzYd8olmjqMpzS+7HiUq6mRsCODc2hGJmfuZR/AczqJsb3SF7MVDMsI76aTt/Tsda+saX5oB7WyUB09hn45eNdg052NRGjIhi7gFHcthm0hUy9HbdF3wBur78=,iv:NpbVI/M4oIUyQgEXfjz5PdscqovTLyvE03VdbEHhuG8=,tag:BpfrKOc6L+CJ0zxxP6Jzrg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
