# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.120.100:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.120.100"
additionalMachineCertSans: *sans

clusterPodNets: ["10.41.120.0/16"]
clusterSvcNets: ["10.43.120.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-ctl-001"
    ipAddress: "192.168.120.101"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:0c:29:9b:9f:45"
        dhcp: false
        addresses:
          - "192.168.120.101/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.120.1"
        mtu: 1500
        vip:
          ip: "192.168.120.100"
  - hostname: "talos-ctl-002"
    ipAddress: "192.168.120.102"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:0c:29:90:6c:0b"
        dhcp: false
        addresses:
          - "192.168.120.102/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.120.1"
        mtu: 1500
        vip:
          ip: "192.168.120.100"
  - hostname: "talos-ctl-003"
    ipAddress: "192.168.120.103"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:0c:29:98:c2:16"
        dhcp: false
        addresses:
          - "192.168.120.103/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.120.1"
        mtu: 1500
        vip:
          ip: "192.168.120.100"
  - hostname: "talos-wrk-001"
    ipAddress: "192.168.120.105"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:0c:29:70:c3:15"
        dhcp: false
        addresses:
          - "192.168.120.105/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.120.1"
        mtu: 1500
  - hostname: "talos-wrk-002"
    ipAddress: "192.168.120.106"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:0c:29:c0:ec:fc"
        dhcp: false
        addresses:
          - "192.168.120.106/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.120.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

