apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:3WxjyATpk/nBk8c=,iv:I9F00L/UmMJvfzpIdqvwsIZVxAGmC3RUvnQg8cZShJI=,tag:2+d8NAaxgdbBTZ3ngRqFgg==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YmJaYndUNDZOV3ZuR1dq
        SG1zdk05b0xPazZtQ0V3bVN4bml5RDJqcWdFClB3YUZLYkY3SnhBTXRwWndFd2NY
        eUw0WWgyS29BR2NSVnBicG4wV281UkUKLS0tIDhGSHA1OFdVdTZRWmRrUVZLSVBM
        YXdTT0phM01XWFNFUjJYUUlud2NXdHcKzzB3+Q+CekF+4S0ofMRhEMQYdVeeyYS3
        TGV3fciHbJdbLGOzg8PADNO4aRx9PVAtSWRAmdlmONpzDPVCE3HRlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:08:50Z"
  mac: ENC[AES256_GCM,data:TlrqQ6S79ZK8NUqQGNPrzB+szWw/6HZ0ZvywIe4deCya1Yg4OlezBO6PE2uE1WxGg8fCGJFnocn1A5mChy+jmbOzCrVtQsqWOiMq053c19O/V8DQXAlAsfdmK53fOVFwulfy8YaIe5HyaNxmS5O4b3XRRDhLK/OzXh/sVuLBMHM=,iv:cXuJK4ZRbHBNcBqPP4o3NXGg+3P9g3RKnLc/Uhg4H5k=,tag:8oUITIJvCn84e7AuWt8+4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
