apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:kJ2onkfiAKxnU24=,iv:lr/suQfnMySETuc7Ne0kQpGju+ZOxPmzu7NTNVhzKBM=,tag:1+5Ksa2N7rs5xiozI5kKJQ==,type:str]
sops:
  age:
    - recipient: age19nxy2s6an4akrcwya68ynn0ymlsuq80uxnz0r09q360r8ftnx94sncahkw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZk0waTh0YlE4WnRraHNT
        K3A3eEgyMUl2OGViYmJ1aTNwdkVJeU1CSlVRClp2QmRRS1VMQTBhd3E0aFlDWExG
        Z1VTVFU2TW8yTkp1Y2ZRUEYyZjZrS0EKLS0tIHlmZTI3blhjb1RzUjU5bFpyR1Zh
        dHpPditjMnVHK3VBMUN1cEtsV1k1Q1kK1x13D2AcrHVfygyQgkwcsvf3OXFhDrU5
        eG8nkAnNq0CgeQ9GPnyHcZszvT3yTNcsUvVe9J1KY0oQAuXLr3UcPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-28T12:34:01Z"
  mac: ENC[AES256_GCM,data:M7SqJIwxw0Y8eyPvOywENOG+yOQT78ARbsQmMSATjvp6NQPK3ZYDStutt3e4vwlpt03nv6aCN5lkygVKOhp9uPQ4aouOA1uxDwOnvrDwNoXJhuDLtJDCrFe/ph0JtIKNdOvfkPrOxGqqTHarAQkHFbdbqqYNA/jsul6kD8YcZ7k=,iv:O5O8w1QFf72E6fuU3ZjERo2Z/ihZFpuK5xXf7Yw6PKc=,tag:FLEdWDZ81licf5nm99pApw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
