apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:t9KH3onh7Hw7epw=,iv:uxi/nYM8E+xIqq+m3bXydRyAF4OUSFhKHKuXwGUIpio=,tag:E08yaCUdnvrUGdOkK9sBFA==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZTV1VjdiQ0NLNG9ra01o
        WWJqbzhhSXlDWER3R3ZGbG1NN3NJZGNHUjBzCnFJcVRYcnFwMEFxaTJtWjVGTUVu
        NDR4dXdjamVrYkVBQWxNeWZIYXV1ZDAKLS0tIEgwM2NRNGNUZ05DYUVsTHZtWnVX
        SE1RUWNndDN2clRWTWoxb2pqTFlzMHcK6mrFXBpI43xn4yKwzxgli8jixDz1Er5Q
        JsBSOsPKDGnO9Ut2QTnsMgXZw/gL7Rp7583LSof7ulqkmSBAq5bhdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:35:27Z"
  mac: ENC[AES256_GCM,data:dtjxuvr+oCroXHUJ1oeUhUbUQ1YtHZ5I30LBVKF9gsUlyMPAXjd6Zutl9J//qTG07TijDq7BP2wpwfL2I2jm8jWX9dk7FknKHWbqX2PCpBQHhbXsZEthoLFkp3HAwJNSt13xRAyff3WkJlCintW9iZOcY6jAwV23SjlnvP+juuA=,iv:z9nEtobC/LQkxQd9NWw6sdNAvDjM0ULdB/dUCMtFqq8=,tag:GirhIU1/ySWonKPXB763qA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
