apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:9OdTO3k5M2Ccxww=,iv:R7sltfYwbz7w1ZCVfJpJXgtcbRKAx1Ho6WggoM8yNvk=,tag:ZJ8CoeTvCWhkMR58kxmZIA==,type:str]
sops:
  age:
    - recipient: age19nxy2s6an4akrcwya68ynn0ymlsuq80uxnz0r09q360r8ftnx94sncahkw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIakRZT0tvaFlEdzFTS3ZJ
        cjJNZmRZUWhRYVRRWnpEcjRBNFM1dithRXpJCjdaYmdQa1JGQ29pQUFibTFIMCtm
        VVR1MnROUk0yY1lKNG81UGh6QVJIc1UKLS0tIGh5Q0xmOW5IaFZNOGNKZm96bllt
        NUJLTW9ZNmRCSEttTmUrSnphNDdvb28KLUdQBvG1CKV5agkfGRdRZLShPSKE+hEo
        Sd3QmxcXIEdp1omUwpR2XKL/jNgUfRO4fuhb3RvvkXcgKmdOYuKPKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-28T12:41:32Z"
  mac: ENC[AES256_GCM,data:ZSmhUePbfWYgv+or6V+CkSW4986yaKN5Ls6up53Z6LRu9ghkAtpJN801kjBNKT9bjMzZeoIH9ItIRruZkey0dMuKnQXJROf0TafeNgNoaAHlwmya/2iZbVqBcl3wZxauUz1a4zUlDGXdoxXoZ4NVyKx2D4q7LYDC07CRJZhJ8ug=,iv:Oderi99EZywd969pYV2JKn6acMSgGWh7N/1KzzRrnh0=,tag:RxWtEMYNcmhoTkzoMwfcwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
