apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:m/TU8q7tmFlaoek=,iv:GmS6G+F90cHKT4CtOjMWZnLzFOt15O1v5hZRNdZ/zAM=,tag:e8o5uNxUc+QaPgi7oIMG0g==,type:str]
sops:
  age:
    - recipient: age175cfg4z5al52cgwvtxwjexdv9z8df5anyqzv9p4cpdlxrzdgzynqsu6ymc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ0lKdVQ0UURod0ZzcG5j
        ODRSUnpJbXpERFpqTUE1azRGQm0zNTVrMzJ3Ck1SanIycGRwTFk3aU40cmNtbzhY
        TGNKUWlDT3ljL3Rua0ZyQ1dGWlJBSzgKLS0tIHZ1VzBZU25WU2kraE9RNlpaS1Bz
        UWl0Ti9TYlJGd1Uxa2dhZ2xES2FVMkEKdS+wPVspzXCbzve9x3mw9YgAIcKjoQLR
        3iWZn/PVmelSC3VvIKebdOpR+LopJvYuePgarjjAbVsT05+UxIQRKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-10T20:00:16Z"
  mac: ENC[AES256_GCM,data:S48es+kf2sbmJAzhoSpuok0hQMuUYp4hou3YLEmJfpvPBWbRDTbsY619/TrmTaJjL89aGjqHT+qPMPCreM/eE4sVFNldEDDRhCNG1OcGU1YPs3bqsYN1zDzouhktVTR++VR7q0g4oOupBzcKZrJ0pkpDxKbtXgq/pngk3TjVVqg=,iv:Co3X3/d35urNkWbEB5O9ss8zMgWxTqpCayKVs08Kx+I=,tag:phn8mqe40urGBAK3bY+K0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
